name: CI

on: [push, pull_request, release]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@2

        # We don't need to setup node with a specific version.
        # NVM is bundled with ubuntu images:
        # https://github.com/actions/setup-node/issues/32#issuecomment-656144527

      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn test

  release:
    needs: test
    name: Release
    runs-on: ubuntu-latest

    if: ${{ startsWith(github.ref, 'refs/tags/v') && github.event_name == 'release' }}

    steps:
      - name: Checkout
        uses: actions/checkout@2

      - env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: echo "RELEASE_TAG=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: echo "Publishing $RELEASE_TAG to npm ..."
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > "$HOME/.npmrc"
      - run: lerna publish from-git --yes --pre-dist-tag next

  website:
    name: Deploy Website
    runs-on: ubuntu-latest

    if: ${{ github.ref == 'refs/heads/website' }}

    steps:
      - name: Checkout
        uses: actions/checkout@2

      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: echo "Deploying website to https://reach.tech/"
      - run: openssl aes-256-cbc -K $encrypted_e12d3fc86b46_key -iv $encrypted_e12d3fc86b46_iv -in website-deploy-key.enc -out website-deploy-key -d
      - run: chmod 600 website-deploy-key
      - run: eval $(ssh-agent -s)
      - run: ssh-add website-deploy-key
      - run: bash scripts/deploy-website.sh
